### ISSUE TITLE
Please Add version 1.0.2

### ISSUE THREAD

**Issue by mcgraphix** [webjars/angular-ui-calendar#3]

**Comment by jamesward** [comment]
That release doesn't exist: https://github.com/angular-ui/ui-calendar/releases

**Comment by mcgraphix** [comment]
Weird... on the webjars site it is listed in the NPM and bower releases.

**Comment by jamesward** [comment]
They probably just forgot to push a tag.

**Comment by couturierb** [comment]
Hello, the version 1.0.2 was released, can you add webjars please ?

Thanks !
